"""This module was auto-generated by datajoint from an existing schema"""


import datajoint as dj

schema = dj.Schema('arseny_s1alm_misc')


vmod0 = dj.VirtualModule('vmod0', 'arseny_s1alm_experiment')
vmod1 = dj.VirtualModule('vmod1', 'arseny_s1alm_ephys')


@schema
class S1TrialTypeName(dj.Imported):
    definition = """
    -> vmod0.SessionTrial
    -> vmod0.TrialNameType
    ---
    trial_type_name2     : varchar(200)                 # descriptive trial type name
    original_trial_type_name : varchar(200)                 # original trial-type name from Solo/Bpod
    """


@schema
class S1StimType(dj.Lookup):
    definition = """
    # S1StimType
    stim_type="nostim"   : varchar(24)                  # sample or distractor or no-stim
    """


@schema
class S1StimPowerType(dj.Lookup):
    definition = """
    # S1StimPowerType
    stim_power_type="NoStim" : varchar(100)                 # stim power category (e.g. full or mini)
    ---
    stim_power_type_description : varchar(4000)                
    """


@schema
class S1PhotostimTrial(dj.Imported):
    definition = """
    # S1PhotostimTrial
    -> vmod0.SessionTrial
    stim_num             : tinyint                      # resets for every trial
    ---
    -> S1StimType
    -> S1StimPowerType
    onset=null           : double                       # onset of the stimulation relative to the go-cue (s); None for no-stim trials
    power=null           : double                       # laser power (mW)
    duration=null        : double                       # total stimulation duration (s)
    """


@schema
class UnitWaveformComment(dj.Manual):
    definition = """
    -> vmod1.Unit
    unit_waveform_comment : varchar(767)                 
    """